feature/arcwell-398/server_production_build
arcweb/arcwell pull request #202
Opened 2024-10-22 17:33 UTC by hswope-arcweb

Updated Dockerfile and package.json to support production server builds.
Fixed bug in PersonFactory.

2024-10-23 17:19 UTC, timgetz requested changes
@hswope-arcweb Looks good, but please add some instructions in the README about building for production.

2024-10-23 17:19 UTC, timgetz commented on packages/server/Dockerfile
> +RUN rm ./build/ace.js
We will need ace for production.  e.g. to run migrations, and/or seed app data.  Does removing this, remove ace commands?

2024-10-23 18:41 UTC, hswope-arcweb commented on packages/server/Dockerfile
> +RUN rm ./build/ace.js
Fixed.

2024-10-24 19:44 UTC, timgetz submitted a review, later dismissed

2024-10-24 20:26 UTC, mccolin reviewed
This looks good to me, but I will defer to @timgetz for a final approval and merge with other `Dockerfile` work you may have underway.

2024-10-24 20:26 UTC, mccolin commented on README.md
> +
I took a crack at editing this paragraph to reflect the goal of showing we offer production-ready builds and linking out to a special `builds.md` with further instructions.

2024-10-24 20:26 UTC, mccolin commented on doc/builds.md
> +
I moved these notes from `packages/README.md` to here. Moving forward, the `/doc` path should hold most content like this. The intention of the `packages/README.md` is to server more as an index of the included packages, which will be especially useful as the set of packages grows.

2024-10-24 20:40 UTC, timgetz approved these changes

2024-10-24 20:40 UTC, merged